name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install backend dependencies
      working-directory: marketmate-mvp/marketmate/backend
      run: npm install

    - name: Run backend tests
      working-directory: marketmate-mvp/marketmate/backend
      run: npm test

    - name: Install frontend dependencies
      working-directory: marketmate-mvp/web_static
      run: npm install

    - name: Run frontend tests
      working-directory: marketmate-mvp/web_static
      run: npm test

    - name: Build frontend
      working-directory: marketmate-mvp/web_static
      run: npm run build

