name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the required Python version

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install cloud-init
      run: |
        sudo apt-get update
        sudo apt-get install -y cloud-init

    - name: Install dependencies
      run: |
        python -m venv marketmate/myenv
        source marketmate/myenv/bin/activate
        pip install -r requirements.txt  # Assuming you have a requirements.txt file for Python dependencies
        bundle install

    - name: Run tests
      run: |
        # Add commands to run your tests, for example:
        # bundle exec rspec
        echo "Tests go here"

