name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjusted to use Node.js 16 to avoid potential compatibility issues

    - name: Install backend dependencies
      run: npm install
      working-directory: ./

    - name: Run backend tests
      run: npm test
      working-directory: ./

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./web_static

    - name: Run frontend tests
      run: npm test
      working-directory: ./web_static

    - name: Build frontend
      run: npm run build
      working-directory: ./web_static

